server:
  port: 8081
security:
  oauth2:
    client:
      client-id: client
      id: client
      client-secret: secret
      registration:
        client-id: client
        id: client
        client-secret: secret


clients:
  registeredClients:
    -
      id: client1
      clientSecret: secret
      grantType:
        - authorization_code
      scope:
        - user_info
        - read
        - write
      registeredRedirectURI:
        - https://www.getpostman.com/oauth2/callback
        - https://resolver.ebscohost.com/openurl
    -
      id: client2
      clientSecret: secret
      grantType:
        - authorization_code
      scope:
        - user_info
        - read
        - write
      registeredRedirectURI:
        - https://www.getpostman.com/oauth2/callback
        - https://resolver.ebscohost.com/openurl