server:
  port: 8081
security:
  oauth2:
    client:
      client-id: client
      id: client
      client-secret: secret
      registration:
        client-id: client
        id: client
        client-secret: secret

#TODO: Get real Client details.
clients:
  registeredClients:
    -
      id: webauth
      clientSecret: secret
      grantType:
        - authorization_code
      scope:
        - user_info
        - read
        - write
      registeredRedirectURI:
        - https://www.getpostman.com/oauth2/callback
        - https://resolver.ebscohost.com/openur
      loginUrl: http://auth-edc.ebscohost.com/login.aspx

    -
      id: client2
      clientSecret: secret
      grantType:
        - authorization_code
      scope:
        - user_info
        - read
        - write
      registeredRedirectURI:
        - https://www.getpostman.com/oauth2/callback
        - https://resolver.ebscohost.com/openurl
      loginUrl: http://auth.devqa.ebsco.zone/api/oidcprovider